/**
 * Sahayak AI — Make.com Webhook Integration
 * Triggers SMS, email, and health alerts via Make.com automations.
 * Set VITE_MAKECOM_SMS_WEBHOOK, VITE_MAKECOM_EMAIL_WEBHOOK, VITE_MAKECOM_ALERT_WEBHOOK in .env
 */

const SMS_WEBHOOK   = import.meta.env.VITE_MAKECOM_SMS_WEBHOOK   as string | undefined
const EMAIL_WEBHOOK = import.meta.env.VITE_MAKECOM_EMAIL_WEBHOOK  as string | undefined
const ALERT_WEBHOOK = import.meta.env.VITE_MAKECOM_ALERT_WEBHOOK  as string | undefined

async function callWebhook(url: string, payload: Record<string, unknown>): Promise<boolean> {
  try {
    await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...payload, timestamp: new Date().toISOString(), source: "sahayak-ai" }),
    })
    return true
  } catch {
    return false
  }
}

/** Send an SMS via Make.com → MSG91/Twilio scenario */
export async function sendSMS(phone: string, message: string): Promise<boolean> {
  if (!SMS_WEBHOOK) { console.warn("VITE_MAKECOM_SMS_WEBHOOK not set"); return false }
  return callWebhook(SMS_WEBHOOK, { phone, message })
}

/** Send an email via Make.com → Gmail/SendGrid scenario */
export async function sendEmail(
  to: string,
  subject: string,
  html: string,
  patientName?: string
): Promise<boolean> {
  if (!EMAIL_WEBHOOK) { console.warn("VITE_MAKECOM_EMAIL_WEBHOOK not set"); return false }
  return callWebhook(EMAIL_WEBHOOK, { to, subject, html, patientName })
}

/** Fire a high-risk/emergency alert — triggers SMS + email + push via Make.com */
export async function triggerAlert(patient: {
  name: string
  phone?: string
  risk_level: string
  diagnosis?: string
  health_score?: number
  village?: string
  ashaPhone?: string
}): Promise<boolean> {
  if (!ALERT_WEBHOOK) { console.warn("VITE_MAKECOM_ALERT_WEBHOOK not set"); return false }
  return callWebhook(ALERT_WEBHOOK, {
    ...patient,
    alert_type: patient.risk_level === "EMERGENCY" ? "emergency" : "high_risk",
    message: `⚠️ ${patient.risk_level} ALERT: ${patient.name} — ${patient.diagnosis ?? "Assessment needed"} (${patient.village ?? "unknown village"})`,
  })
}

/** Send appointment reminder SMS to patient */
export async function sendAppointmentReminder(
  phone: string,
  patientName: string,
  doctorName: string,
  dateTime: string
): Promise<boolean> {
  const msg = `नमस्ते ${patientName}! आपकी ${doctorName} से appointment ${dateTime} को है। — Sahayak AI`
  return sendSMS(phone, msg)
}

/** Send daily health tip to patient */
export async function sendDailyHealthTip(
  phone: string,
  tip: string,
  language: "hi" | "kn" | "en" = "hi"
): Promise<boolean> {
  const prefix = language === "hi" ? "🌿 आज की स्वास्थ्य सलाह: " : language === "kn" ? "🌿 ಇಂದಿನ ಆರೋಗ್ಯ ಸಲಹೆ: " : "🌿 Health tip: "
  return sendSMS(phone, prefix + tip + " — Sahayak AI")
}

/** Email full patient report PDF link */
export async function emailPatientReport(
  doctorEmail: string,
  patientName: string,
  reportSummary: string
): Promise<boolean> {
  return sendEmail(
    doctorEmail,
    `Patient Report: ${patientName} — Sahayak AI`,
    `<h2>Patient Report: ${patientName}</h2><pre>${reportSummary}</pre><br><small>Generated by Sahayak AI on ${new Date().toLocaleString()}</small>`,
    patientName
  )
}
